---
name: Spellcheck

on:
  - push

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build spellcheck tooling container
        env:
          DOCKER_BUILDKIT: 1
        run: docker build --tag spellchecker --target spellchecker .
      - name: Spellcheck all adoc files
        run: docker run --rm --volume ${GITHUB_WORKSPACE}:/workspace --workdir /workspace spellchecker ./bin/spellcheck-ci.py