name: Generate Antora site

on:
  push:
    branches:
      - main
      - add-actions
      
env:
  SITE_DIR: 'site'

jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
         antora_playbook: antora-playbook.yml
         site_sources_path: ./

      - name: "List folder"
        run: |
          ls -ltra $GITHUB_WORKSPACE/build/$SITE_DIR

      - name: "Upload generated site"
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
       
  deploy_site:
    runs-on: ubuntu-latest
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
     - name: Setup Node.js for use with actions
       uses: actions/setup-node@v2
       with:
         node-version: '16'

     - name: Checkout
       uses: actions/checkout@v2

     - name: Download generated site
       uses: actions/download-artifact@v2
       with:
         name: site
         path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
  
  secure_copy:
    runs-on: ubuntu-latest
    needs: [deploy_site]
    name: "Secure copy site to coppi"
    steps:
# add SSH known hosts for secure copy
     - name: Install SSH Key
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SSH_PRIVATE_KEY }} 
         name: github-actions
         known_hosts: unnecessary

# append known hosts    
#     - name: Add Known Hosts
#       run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  
     - name: copy file via ssh key
       uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
#        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "site"
        target: "."