name: Generate Antora site

on:
  push:
    branches:
      - main
      - add-actions
      
env:
  SITE_DIR: 'site'
jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
         antora_playbook: antora-playbook.yml
         site_sources_path: ./

      - name: "List folder"
        run: |
          ls -ltra $GITHUB_WORKSPACE/build/$SITE_DIR/ctool/latest
      - name: "Upload generated site"
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
       
  deploy_site:
    runs-on: ubuntu-latest
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
     - name: Setup Node.js for use with actions
       uses: actions/setup-node@v2
       with:
         node-version: '16'

     - name: Checkout
       uses: actions/checkout@v2

     - name: Download generated site
       uses: actions/download-artifact@v2
       with:
         name: site
         path: "${{ github.workspace }}/${{ env.SITE_DIR }}"

# scp copy
     - name: Secure copy with ENV
       uses: garygrossgarten/github-action-scp@release
       with:
        local: "${{ github.workspace }}/build/${{ env.SITE_DIR }}"
        remote: https://docsreview.sjc.dsinternal.org/en/test
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        privateKey: ${{ secrets.PRIVATE_KEY}}
        rmRemote: true
        dotfiles: true 