name: test-ssh
on:
  push:
    branches:
      - main
      - add-actions
      
env:
  SITE_DIR: 'site'
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  SSH_PORT: ${{ secrets.SSH_PORT }} 
  SSH_HOST: ${{ secrets.SSH_KNOWN_HOSTS }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.SSH_KNOWN_HOSTS }}
       username: ${{ secrets.SSH_USER }}
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       port: ${{ secrets.SSH_PORT }}
       script: whoami
